import type { MuscleId } from "@/lib/muscles";

export type ExerciseCategory = "chest" | "back" | "shoulders" | "arms" | "core" | "legs";

export const EXERCISE_CATEGORIES: { value: ExerciseCategory; label: string }[] = [
  { value: "chest", label: "Грудь" },
  { value: "back", label: "Спина" },
  { value: "shoulders", label: "Плечи" },
  { value: "arms", label: "Руки" },
  { value: "core", label: "Пресс и корпус" },
  { value: "legs", label: "Ноги" },
];

export type Exercise = {
  id: string;
  name: string;
  category: ExerciseCategory;
  equipment: string;
  focus: string;
  technique: string[];
  primary: MuscleId[];
  secondary: MuscleId[];
  stabilizer: MuscleId[];
};

export const EXERCISES: Exercise[] = [
  // ───────────────────────── ГРУДЬ ─────────────────────────
  {
    id: "incline-barbell-press",
    name: "Жим штанги на наклонной скамье вверх",
    category: "chest",
    equipment: "Штанга, наклонная скамья",
    focus: "Верх груди (ключичная часть)",
    technique: [
      "Скамья под углом 30–45°: больше угол — больше уходит нагрузка в передние дельты.",
      "Лопатки сведены и прижаты, стопы твёрдо на полу.",
      "Опускай штангу к верхней части груди (под ключицы), локти ~45° к корпусу.",
      "Выжимай вверх по слегка наклонной дуге, к линии глаз.",
    ],
    primary: ["chest_upper"],
    secondary: ["delt_front", "triceps_lateral", "triceps_long", "chest_mid"],
    stabilizer: ["serratus", "abs_upper", "traps_mid", "biceps_long"],
  },
  {
    id: "bench-press",
    name: "Жим штанги лёжа горизонтально",
    category: "chest",
    equipment: "Штанга, скамья",
    focus: "Середина груди + общий объём",
    technique: [
      "Ляг на скамью, лопатки сведены и прижаты, естественный прогиб в пояснице, стопы твёрдо на полу.",
      "Хват чуть шире плеч, гриф над серединой груди.",
      "Опусти штангу к низу груди по контролируемой траектории, локти под углом ~45° к корпусу.",
      "Мощно выжми штангу вверх, не отрывая таз от скамьи.",
    ],
    primary: ["chest_mid", "chest_low"],
    secondary: ["delt_front", "triceps_lateral", "triceps_long", "triceps_medial"],
    stabilizer: ["serratus", "abs_upper", "lats_upper", "forearm_flexors"],
  },
  {
    id: "decline-bench-press",
    name: "Жим штанги на наклонной скамье вниз",
    category: "chest",
    equipment: "Штанга, скамья с отрицательным наклоном",
    focus: "Низ груди (рёберная часть)",
    technique: [
      "Скамья с наклоном вниз 15–30°, ноги надёжно зафиксированы.",
      "Опускай штангу к нижней части груди, локти ближе к корпусу, чем в обычном жиме.",
      "Выжимай вверх, не выпрямляя локти в жёсткий замок.",
    ],
    primary: ["chest_low"],
    secondary: ["chest_mid", "triceps_lateral", "triceps_long", "delt_front"],
    stabilizer: ["serratus", "abs_upper"],
  },
  {
    id: "incline-db-press",
    name: "Жим гантелей на наклонной скамье",
    category: "chest",
    equipment: "Гантели, наклонная скамья",
    focus: "Верх груди, больше амплитуда чем со штангой",
    technique: [
      "Скамья под углом 30–45°.",
      "Гантели у верхней части груди, локти под кистями.",
      "Выжимай вверх-вперёд по дуге, вверху гантели почти соприкасаются.",
      "Опускай глубже, чем позволяет штанга, — до растяжения груди.",
    ],
    primary: ["chest_upper"],
    secondary: ["delt_front", "triceps_lateral", "triceps_long", "chest_mid"],
    stabilizer: ["serratus", "abs_upper", "biceps_short", "forearm_flexors"],
  },
  {
    id: "db-bench-press",
    name: "Жим гантелей лёжа",
    category: "chest",
    equipment: "Гантели, скамья",
    focus: "Середина груди, больше работы стабилизаторов",
    technique: [
      "Лёжа на скамье, гантели над грудью, ладони смотрят вперёд.",
      "Опускай гантели по дуге до уровня груди, локти не разводи слишком широко.",
      "Выжимай вверх, слегка сводя гантели вверху, не сталкивая их.",
    ],
    primary: ["chest_mid"],
    secondary: ["chest_low", "delt_front", "triceps_lateral", "triceps_long"],
    stabilizer: ["serratus", "abs_upper", "biceps_short", "forearm_flexors"],
  },
  {
    id: "db-flyes",
    name: "Разведение гантелей лёжа",
    category: "chest",
    equipment: "Гантели, скамья",
    focus: "Растяжение и внутренняя часть груди, изоляция",
    technique: [
      "Лёжа на скамье, руки над грудью с лёгким сгибом в локтях (угол зафиксирован).",
      "Разводи руки по дуге в стороны, чувствуя растяжение груди, не ниже уровня плеч.",
      "Своди обратно тем же путём, ведя движение грудью, а не руками.",
    ],
    primary: ["chest_mid"],
    secondary: ["chest_upper", "chest_low", "delt_front"],
    stabilizer: ["biceps_short", "serratus", "abs_upper"],
  },
  {
    id: "cable-crossover",
    name: "Сведение рук в кроссовере",
    category: "chest",
    equipment: "Блочный тренажёр",
    focus: "Низ и внутренняя часть груди (блоки сверху)",
    technique: [
      "Встань по центру между блоками, лёгкий наклон вперёд.",
      "Своди руки по дуге перед собой, слегка сгибая локти.",
      "В нижней точке — пауза и сокращение груди, затем медленно возвращай руки назад.",
      "Блоки сверху — акцент на низ груди, блоки снизу — на верх.",
    ],
    primary: ["chest_low", "chest_mid"],
    secondary: ["chest_upper", "delt_front", "serratus"],
    stabilizer: ["abs_upper", "obliques", "erector"],
  },
  {
    id: "dips-chest",
    name: "Отжимания на брусьях (грудной акцент)",
    category: "chest",
    equipment: "Брусья",
    focus: "Низ груди",
    technique: [
      "Корпус наклонён вперёд, локти разводи в стороны.",
      "Опускайся, пока не почувствуешь растяжение груди, без боли в плечах.",
      "Выжимай вверх, сохраняя наклон корпуса вперёд.",
    ],
    primary: ["chest_low"],
    secondary: ["triceps_long", "triceps_lateral", "delt_front", "chest_mid"],
    stabilizer: ["abs_upper", "abs_lower", "serratus", "lats_lower"],
  },
  {
    id: "pushups",
    name: "Отжимания от пола",
    category: "chest",
    equipment: "Собственный вес",
    focus: "Середина груди + корпус",
    technique: [
      "Руки чуть шире плеч, тело — прямая линия от головы до пяток.",
      "Опускайся, пока грудь почти не коснётся пола, локти под ~45°.",
      "Выжимай вверх, не прогибая поясницу.",
    ],
    primary: ["chest_mid"],
    secondary: ["chest_low", "delt_front", "triceps_lateral", "triceps_long"],
    stabilizer: ["abs_upper", "abs_lower", "serratus", "glute_max", "erector"],
  },
  {
    id: "pullover",
    name: "Пуловер с гантелью",
    category: "chest",
    equipment: "Гантель, скамья",
    focus: "Растяжение груди и широчайших, грудная клетка",
    technique: [
      "Ляг поперёк или вдоль скамьи, гантель в двух руках над грудью.",
      "Опускай гантель за голову по дуге, сохраняя лёгкий сгиб в локтях.",
      "Возвращай в исходное, ведя движение грудью и широчайшими.",
    ],
    primary: ["chest_mid", "lats_upper"],
    secondary: ["serratus", "triceps_long", "chest_low"],
    stabilizer: ["abs_upper", "delt_front", "traps_low"],
  },

  // ───────────────────────── СПИНА ─────────────────────────
  {
    id: "deadlift",
    name: "Становая тяга",
    category: "back",
    equipment: "Штанга",
    focus: "Задняя цепь целиком: спина, ягодицы, бицепс бедра",
    technique: [
      "Штанга над серединой стопы, хват чуть шире ног.",
      "Спина прямая, грудь вперёд, таз отведён назад — поясницу не круглить.",
      "Тяни штангу вдоль голеней вверх, разгибая ноги и корпус одновременно.",
      "В верхней точке — таз вперёд, плечи назад, без переразгиба поясницы.",
    ],
    primary: ["erector", "glute_max", "ham_biceps", "ham_semi"],
    secondary: ["traps_upper", "traps_mid", "lats_lower", "quad_rectus", "quad_lateral", "adductors"],
    stabilizer: ["forearm_flexors", "abs_upper", "abs_lower", "obliques", "calf_gastro", "rhomboids"],
  },
  {
    id: "pull-ups",
    name: "Подтягивания широким хватом",
    category: "back",
    equipment: "Турник",
    focus: "Ширина спины — верх широчайших",
    technique: [
      "Хват шире плеч, вис на прямых руках.",
      "Тяни корпус вверх, сводя лопатки, ведя движение локтями вниз-назад.",
      "Подбородок над перекладиной, затем контролируемо опускайся до полного выпрямления рук.",
    ],
    primary: ["lats_upper", "lats_lower"],
    secondary: ["teres", "biceps_long", "brachialis", "rhomboids", "traps_mid", "traps_low", "delt_rear"],
    stabilizer: ["forearm_flexors", "abs_lower", "erector"],
  },
  {
    id: "chin-ups",
    name: "Подтягивания обратным хватом",
    category: "back",
    equipment: "Турник",
    focus: "Низ широчайших + сильный акцент на бицепс",
    technique: [
      "Обратный хват на ширине плеч, вис на прямых руках.",
      "Тяни себя вверх, локти идут вниз вдоль корпуса.",
      "Опускайся медленно, полностью выпрямляя руки внизу.",
    ],
    primary: ["lats_lower", "biceps_long", "biceps_short"],
    secondary: ["lats_upper", "brachialis", "rhomboids", "traps_mid", "teres"],
    stabilizer: ["forearm_flexors", "abs_lower", "erector"],
  },
  {
    id: "lat-pulldown",
    name: "Тяга верхнего блока",
    category: "back",
    equipment: "Блочный тренажёр",
    focus: "Ширина спины, вариант подтягиваний с регулируемым весом",
    technique: [
      "Хват шире плеч, корпус слегка отклонён назад.",
      "Тяни рукоять к верхней части груди, сводя лопатки и опуская локти вниз.",
      "Медленно возвращай вес, полностью растягивая широчайшие вверху.",
    ],
    primary: ["lats_upper", "lats_lower"],
    secondary: ["teres", "biceps_long", "biceps_short", "rhomboids", "traps_mid", "delt_rear"],
    stabilizer: ["forearm_flexors", "erector", "abs_upper"],
  },
  {
    id: "barbell-row",
    name: "Тяга штанги в наклоне",
    category: "back",
    equipment: "Штанга",
    focus: "Толщина спины — середина, ромбовидные",
    technique: [
      "Наклон корпуса ~45°, спина прямая, колени чуть согнуты.",
      "Тяни штангу к низу живота, локти идут вдоль корпуса назад.",
      "В верхней точке сведи лопатки, затем медленно опусти штангу.",
    ],
    primary: ["lats_lower", "lats_upper", "rhomboids"],
    secondary: ["traps_mid", "traps_low", "delt_rear", "teres", "biceps_long", "brachialis"],
    stabilizer: ["erector", "ham_biceps", "glute_max", "forearm_flexors", "abs_upper"],
  },
  {
    id: "db-row",
    name: "Тяга гантели одной рукой в наклоне",
    category: "back",
    equipment: "Гантель, скамья",
    focus: "Толщина спины, работа каждой стороны отдельно",
    technique: [
      "Обопрись коленом и рукой о скамью, спина параллельна полу.",
      "Тяни гантель к поясу, локоть идёт вдоль корпуса, лопатка сводится к позвоночнику.",
      "Опускай гантель контролируемо до полного растяжения.",
    ],
    primary: ["lats_upper", "lats_lower"],
    secondary: ["rhomboids", "traps_mid", "delt_rear", "biceps_long", "teres", "brachialis"],
    stabilizer: ["obliques", "erector", "forearm_flexors"],
  },
  {
    id: "t-bar-row",
    name: "Тяга Т-грифа",
    category: "back",
    equipment: "Т-гриф",
    focus: "Толщина середины спины",
    technique: [
      "Наклон корпуса ~45°, хват на рукояти, спина прямая.",
      "Тяни гриф к груди/животу, сводя лопатки.",
      "Опускай подконтрольно, не округляя спину.",
    ],
    primary: ["lats_lower", "rhomboids"],
    secondary: ["lats_upper", "traps_mid", "delt_rear", "biceps_long", "teres"],
    stabilizer: ["erector", "ham_biceps", "forearm_flexors", "abs_upper"],
  },
  {
    id: "seated-cable-row",
    name: "Тяга горизонтального блока сидя",
    category: "back",
    equipment: "Блочный тренажёр",
    focus: "Середина спины, ромбовидные, низ трапеции",
    technique: [
      "Сидя, спина прямая, лёгкий наклон корпуса вперёд в растяжении.",
      "Тяни рукоять к животу, сводя лопатки, локти вдоль корпуса.",
      "Возвращай вес подконтрольно, позволяя лопаткам разойтись.",
    ],
    primary: ["rhomboids", "lats_lower", "traps_mid"],
    secondary: ["lats_upper", "traps_low", "delt_rear", "biceps_long", "brachialis"],
    stabilizer: ["erector", "forearm_flexors", "abs_upper"],
  },
  {
    id: "hyperextension",
    name: "Гиперэкстензия",
    category: "back",
    equipment: "Тренажёр для гиперэкстензии",
    focus: "Разгибатели поясницы",
    technique: [
      "Таз на подушке тренажёра, ноги зафиксированы, корпус опущен вперёд.",
      "Поднимай корпус до прямой линии тело-ноги, не переразгибаясь.",
      "Опускай подконтрольно, без рывков.",
    ],
    primary: ["erector"],
    secondary: ["glute_max", "ham_biceps", "ham_semi"],
    stabilizer: ["traps_mid", "abs_upper", "rhomboids"],
  },
  {
    id: "good-morning",
    name: "Наклоны со штангой (гуд морнинг)",
    category: "back",
    equipment: "Штанга",
    focus: "Поясница и бицепс бедра",
    technique: [
      "Штанга на трапециях, колени чуть согнуты, спина прямая.",
      "Наклоняй корпус вперёд, отводя таз назад, до растяжения задней поверхности бедра.",
      "Возвращайся, разгибая корпус за счёт бёдер и поясницы.",
    ],
    primary: ["erector", "ham_biceps", "ham_semi"],
    secondary: ["glute_max", "adductors"],
    stabilizer: ["abs_upper", "abs_lower", "traps_upper", "obliques"],
  },
  {
    id: "shrugs",
    name: "Шраги со штангой или гантелями",
    category: "back",
    equipment: "Штанга / гантели",
    focus: "Верх трапеции",
    technique: [
      "Стоя прямо, вес в опущенных руках.",
      "Поднимай плечи строго вверх, к ушам, без вращения плечами.",
      "В верхней точке — короткая пауза, затем медленно опускай.",
    ],
    primary: ["traps_upper"],
    secondary: ["traps_mid", "rhomboids"],
    stabilizer: ["forearm_flexors", "erector", "delt_side"],
  },
  {
    id: "face-pull",
    name: "Тяга каната к лицу",
    category: "back",
    equipment: "Блочный тренажёр, канат",
    focus: "Задняя дельта, низ трапеции, здоровье плеч",
    technique: [
      "Блок на уровне лица, канат хватом сверху.",
      "Тяни канат к лицу, разводя кисти в стороны, локти выше кистей.",
      "В конечной точке сведи лопатки и разверни плечи наружу, затем медленно верни.",
    ],
    primary: ["delt_rear", "traps_mid"],
    secondary: ["traps_low", "rhomboids", "teres"],
    stabilizer: ["erector", "abs_upper", "forearm_extensors"],
  },

  // ───────────────────────── ПЛЕЧИ ─────────────────────────
  {
    id: "ohp",
    name: "Жим штанги стоя (армейский жим)",
    category: "shoulders",
    equipment: "Штанга",
    focus: "Передняя и средняя дельта, базовое движение",
    technique: [
      "Штанга на уровне ключиц, хват чуть шире плеч, корпус напряжён.",
      "Выжимай штангу строго вверх, слегка уводя голову назад на пути грифа.",
      "В верхней точке руки полностью выпрямлены над головой, штанга над макушкой.",
    ],
    primary: ["delt_front", "delt_side"],
    secondary: ["triceps_long", "triceps_lateral", "traps_upper", "chest_upper"],
    stabilizer: ["abs_upper", "abs_lower", "obliques", "erector", "glute_max", "serratus"],
  },
  {
    id: "db-shoulder-press",
    name: "Жим гантелей сидя",
    category: "shoulders",
    equipment: "Гантели, скамья",
    focus: "Передняя и средняя дельта, больше амплитуда",
    technique: [
      "Сидя с опорой на спинку, гантели на уровне плеч, ладони вперёд.",
      "Выжимай гантели вверх по дуге, не сталкивая их наверху.",
      "Опускай подконтрольно до уровня ушей.",
    ],
    primary: ["delt_front", "delt_side"],
    secondary: ["triceps_long", "triceps_lateral", "traps_upper"],
    stabilizer: ["abs_upper", "serratus", "forearm_flexors"],
  },
  {
    id: "lateral-raise",
    name: "Махи гантелями в стороны",
    category: "shoulders",
    equipment: "Гантели",
    focus: "Средняя дельта — ширина плеч",
    technique: [
      "Стоя, гантели у бёдер, лёгкий сгиб в локтях.",
      "Поднимай руки в стороны до уровня плеч, ведущий сустав — локоть, а не кисть.",
      "Опускай медленно, без рывка и раскачки корпусом.",
    ],
    primary: ["delt_side"],
    secondary: ["delt_front", "traps_upper"],
    stabilizer: ["abs_upper", "erector", "forearm_flexors", "traps_mid"],
  },
  {
    id: "front-raise",
    name: "Махи гантелями вперёд",
    category: "shoulders",
    equipment: "Гантели",
    focus: "Передняя дельта, изоляция",
    technique: [
      "Стоя, гантели у бёдер, лёгкий сгиб в локтях.",
      "Поднимай одну или обе руки вперёд до уровня плеч.",
      "Опускай подконтрольно, без раскачки корпусом.",
    ],
    primary: ["delt_front"],
    secondary: ["delt_side", "chest_upper", "traps_upper"],
    stabilizer: ["abs_upper", "erector", "forearm_flexors"],
  },
  {
    id: "rear-delt-fly",
    name: "Разведение гантелей в наклоне",
    category: "shoulders",
    equipment: "Гантели",
    focus: "Задняя дельта — объём плеча сзади",
    technique: [
      "Наклон корпуса вперёд почти до параллели, гантели свисают под плечами.",
      "Разводи руки в стороны, ведя движение локтями, лопатки слегка сводятся.",
      "Опускай подконтрольно, не раскачивай корпус.",
    ],
    primary: ["delt_rear"],
    secondary: ["rhomboids", "traps_mid", "traps_low", "teres"],
    stabilizer: ["erector", "ham_biceps", "forearm_extensors"],
  },
  {
    id: "upright-row",
    name: "Тяга штанги к подбородку",
    category: "shoulders",
    equipment: "Штанга",
    focus: "Средняя дельта и верх трапеции",
    technique: [
      "Хват чуть уже плеч, штанга у бёдер.",
      "Тяни штангу вдоль корпуса вверх, локти ведут движение и идут выше кистей.",
      "Останавливайся на уровне груди-подбородка, не поднимай через боль в плечах.",
    ],
    primary: ["delt_side", "traps_upper"],
    secondary: ["delt_front", "biceps_short", "rhomboids", "traps_mid"],
    stabilizer: ["forearm_flexors", "abs_upper", "erector"],
  },
  {
    id: "arnold-press",
    name: "Жим Арнольда",
    category: "shoulders",
    equipment: "Гантели",
    focus: "Передняя дельта с полной ротацией плеча",
    technique: [
      "Старт: гантели у груди, ладони к себе.",
      "Выжимая вверх, разворачивай кисти наружу, вверху ладони смотрят вперёд.",
      "Опускай, разворачивая кисти обратно к себе.",
    ],
    primary: ["delt_front", "delt_side"],
    secondary: ["triceps_long", "triceps_lateral", "traps_upper"],
    stabilizer: ["abs_upper", "serratus", "forearm_flexors"],
  },

  // ───────────────────────── РУКИ ─────────────────────────
  {
    id: "barbell-curl",
    name: "Подъём штанги на бицепс",
    category: "arms",
    equipment: "Штанга",
    focus: "Обе головки бицепса, базовое движение на массу",
    technique: [
      "Стоя, хват на ширине плеч, локти прижаты к корпусу.",
      "Сгибай руки, поднимая штангу к груди, не раскачивая корпус.",
      "Опускай подконтрольно до полного выпрямления рук.",
    ],
    primary: ["biceps_long", "biceps_short"],
    secondary: ["brachialis", "forearm_flexors"],
    stabilizer: ["delt_front", "abs_upper", "erector", "traps_upper"],
  },
  {
    id: "db-curl",
    name: "Сгибание рук с гантелями (супинация)",
    category: "arms",
    equipment: "Гантели",
    focus: "Пик бицепса за счёт разворота кисти",
    technique: [
      "Стоя или сидя, гантели по бокам, ладони смотрят внутрь.",
      "Сгибая руку, разворачивай кисть ладонью вверх (супинация).",
      "В верхней точке — короткое сокращение, затем медленно опускай.",
    ],
    primary: ["biceps_long", "biceps_short"],
    secondary: ["brachialis", "forearm_flexors"],
    stabilizer: ["delt_front", "abs_upper"],
  },
  {
    id: "hammer-curl",
    name: "Молотки с гантелями",
    category: "arms",
    equipment: "Гантели",
    focus: "Брахиалис и предплечье — толщина руки сбоку",
    technique: [
      "Гантели по бокам, ладони смотрят друг на друга (нейтральный хват).",
      "Сгибай руки, сохраняя нейтральный хват на всей траектории.",
      "Опускай подконтрольно, не разворачивая кисть.",
    ],
    primary: ["brachialis", "forearm_flexors"],
    secondary: ["biceps_long", "biceps_short"],
    stabilizer: ["delt_front", "abs_upper"],
  },
  {
    id: "scott-curl",
    name: "Сгибание рук на скамье Скотта",
    category: "arms",
    equipment: "Скамья Скотта, штанга/гантели",
    focus: "Короткая головка бицепса, нижняя часть амплитуды",
    technique: [
      "Плечи плотно прижаты к скамье, руки на наклонной опоре.",
      "Сгибай руки, поднимая вес, не отрывая плечи от опоры.",
      "Опускай до почти полного выпрямления, без рывка внизу.",
    ],
    primary: ["biceps_short"],
    secondary: ["biceps_long", "brachialis"],
    stabilizer: ["forearm_flexors", "delt_front"],
  },
  {
    id: "incline-db-curl",
    name: "Сгибание рук сидя на наклонной скамье",
    category: "arms",
    equipment: "Гантели, наклонная скамья",
    focus: "Длинная головка бицепса — в растянутом положении",
    technique: [
      "Сядь на скамью с наклоном 45–60°, руки свободно свисают назад.",
      "Сгибай руки, не выводя локти вперёд — плечо остаётся на месте.",
      "Опускай полностью, чувствуя растяжение бицепса внизу.",
    ],
    primary: ["biceps_long"],
    secondary: ["biceps_short", "brachialis"],
    stabilizer: ["forearm_flexors", "delt_front"],
  },
  {
    id: "close-grip-bench",
    name: "Жим штанги лёжа узким хватом",
    category: "arms",
    equipment: "Штанга, скамья",
    focus: "Трицепс целиком, базовое движение на массу рук",
    technique: [
      "Хват на ширине плеч или чуть уже, локти движутся вдоль корпуса.",
      "Опускай штангу к низу груди, локти не разводи широко.",
      "Выжимай вверх, акцент на разгибание в локтях.",
    ],
    primary: ["triceps_long", "triceps_lateral", "triceps_medial"],
    secondary: ["chest_mid", "chest_low", "delt_front"],
    stabilizer: ["abs_upper", "serratus", "lats_upper", "forearm_flexors"],
  },
  {
    id: "skull-crusher",
    name: "Французский жим лёжа",
    category: "arms",
    equipment: "Штанга/гантели, скамья",
    focus: "Длинная головка трицепса — растяжение",
    technique: [
      "Лёжа, руки с весом подняты вертикально над плечами.",
      "Сгибай руки в локтях, опуская вес к вискам/за голову, плечи неподвижны.",
      "Разгибай руки обратно, работая только предплечьем.",
    ],
    primary: ["triceps_long", "triceps_medial"],
    secondary: ["triceps_lateral"],
    stabilizer: ["delt_front", "abs_upper", "forearm_flexors", "serratus"],
  },
  {
    id: "cable-pushdown",
    name: "Разгибание рук на блоке",
    category: "arms",
    equipment: "Блочный тренажёр",
    focus: "Латеральная головка трицепса — «подкова»",
    technique: [
      "Локти прижаты к корпусу, хват на канате или прямой рукояти сверху.",
      "Разгибай руки вниз до полного выпрямления, не отрывая локти от тела.",
      "Возвращай подконтрольно, не давая весу уйти вверх рывком.",
    ],
    primary: ["triceps_lateral", "triceps_medial"],
    secondary: ["triceps_long"],
    stabilizer: ["abs_upper", "delt_rear", "lats_lower", "forearm_extensors"],
  },
  {
    id: "overhead-triceps",
    name: "Французский жим стоя из-за головы",
    category: "arms",
    equipment: "Гантель / канат",
    focus: "Длинная головка трицепса в максимальном растяжении",
    technique: [
      "Вес над головой, плечи прижаты к ушам и неподвижны.",
      "Опускай вес за голову, сгибая только локти.",
      "Разгибай руки вверх до полного выпрямления.",
    ],
    primary: ["triceps_long"],
    secondary: ["triceps_medial", "triceps_lateral"],
    stabilizer: ["delt_front", "abs_upper", "abs_lower", "erector"],
  },
  {
    id: "dips-triceps",
    name: "Отжимания на брусьях (трицепс акцент)",
    category: "arms",
    equipment: "Брусья",
    focus: "Трицепс, работа с большим весом",
    technique: [
      "Корпус держи вертикально, локти близко к телу.",
      "Опускайся до угла ~90° в локтях.",
      "Выжимай вверх, полностью разгибая руки.",
    ],
    primary: ["triceps_long", "triceps_lateral", "triceps_medial"],
    secondary: ["chest_low", "delt_front"],
    stabilizer: ["abs_upper", "serratus", "lats_lower"],
  },
  {
    id: "wrist-curl",
    name: "Сгибание запястий со штангой",
    category: "arms",
    equipment: "Штанга",
    focus: "Сгибатели предплечья — внутренняя сторона",
    technique: [
      "Предплечья на бедре или скамье, кисти свисают за край, ладони вверх.",
      "Сгибай кисти вверх, поднимая штангу за счёт запястий.",
      "Опускай медленно до полного растяжения.",
    ],
    primary: ["forearm_flexors"],
    secondary: [],
    stabilizer: ["biceps_short", "brachialis"],
  },
  {
    id: "reverse-curl",
    name: "Подъём штанги обратным хватом",
    category: "arms",
    equipment: "Штанга",
    focus: "Разгибатели предплечья и брахиалис",
    technique: [
      "Хват сверху (ладони вниз), на ширине плеч, локти у корпуса.",
      "Сгибай руки, поднимая штангу, кисти держи жёстко в одной линии с предплечьем.",
      "Опускай подконтрольно, вес будет заметно меньше, чем в обычном подъёме.",
    ],
    primary: ["forearm_extensors", "brachialis"],
    secondary: ["biceps_long", "forearm_flexors"],
    stabilizer: ["delt_front", "abs_upper"],
  },

  // ───────────────────────── ПРЕСС И КОРПУС ─────────────────────────
  {
    id: "crunches",
    name: "Скручивания",
    category: "core",
    equipment: "Собственный вес",
    focus: "Верх прямой мышцы живота",
    technique: [
      "Лёжа на спине, колени согнуты, руки за головой без давления на шею.",
      "Скручивай корпус, отрывая лопатки от пола за счёт пресса.",
      "Медленно возвращайся, не расслабляя пресс полностью внизу.",
    ],
    primary: ["abs_upper"],
    secondary: ["abs_lower", "obliques"],
    stabilizer: ["quad_rectus"],
  },
  {
    id: "leg-raises",
    name: "Подъём ног в висе",
    category: "core",
    equipment: "Турник",
    focus: "Низ пресса",
    technique: [
      "Вис на турнике, ноги прямые или чуть согнуты.",
      "Поднимай ноги вперёд-вверх за счёт пресса, подкручивая таз, без раскачки.",
      "Опускай подконтрольно, не бросая ноги вниз.",
    ],
    primary: ["abs_lower"],
    secondary: ["abs_upper", "obliques", "quad_rectus"],
    stabilizer: ["forearm_flexors", "lats_lower", "adductors"],
  },
  {
    id: "reverse-crunch",
    name: "Обратные скручивания",
    category: "core",
    equipment: "Собственный вес",
    focus: "Низ пресса, без нагрузки на шею",
    technique: [
      "Лёжа на спине, руки вдоль тела, ноги согнуты под 90°.",
      "Подтягивай колени к груди, отрывая таз от пола за счёт пресса.",
      "Опускай медленно, не бросая ноги на пол.",
    ],
    primary: ["abs_lower"],
    secondary: ["abs_upper", "obliques"],
    stabilizer: ["quad_rectus", "adductors"],
  },
  {
    id: "plank",
    name: "Планка",
    category: "core",
    equipment: "Собственный вес",
    focus: "Статика всего кора",
    technique: [
      "Упор на предплечья и носки, тело — прямая линия от головы до пяток.",
      "Напряги пресс и ягодицы, не прогибай и не поднимай таз.",
      "Держи позицию заданное время, дыши ровно.",
    ],
    primary: ["abs_upper", "abs_lower"],
    secondary: ["obliques", "erector", "serratus"],
    stabilizer: ["delt_front", "glute_max", "quad_rectus", "traps_mid"],
  },
  {
    id: "russian-twist",
    name: "Русские скручивания",
    category: "core",
    equipment: "Собственный вес / диск",
    focus: "Косые мышцы, ротация корпуса",
    technique: [
      "Сидя, корпус отклонён назад, ноги слегка приподняты или на полу.",
      "Поворачивай корпус в стороны, касаясь пола рядом с бедром.",
      "Двигайся плавно, без рывков, сохраняя напряжение пресса.",
    ],
    primary: ["obliques"],
    secondary: ["abs_upper", "abs_lower"],
    stabilizer: ["erector", "quad_rectus", "adductors"],
  },
  {
    id: "side-bend",
    name: "Наклоны в стороны с гантелью",
    category: "core",
    equipment: "Гантель",
    focus: "Косые мышцы, боковое сгибание",
    technique: [
      "Стоя, гантель в одной руке, вторая рука за головой или на поясе.",
      "Наклоняйся строго в сторону, не заваливая корпус вперёд/назад.",
      "Возвращайся в исходное положение, работая косыми мышцами.",
    ],
    primary: ["obliques"],
    secondary: ["erector", "abs_upper"],
    stabilizer: ["traps_upper", "forearm_flexors", "glute_med"],
  },
  {
    id: "cable-woodchopper",
    name: "Дровосек на блоке",
    category: "core",
    equipment: "Блочный тренажёр",
    focus: "Косые мышцы в динамической ротации",
    technique: [
      "Блок сверху, рукоять в двух руках, стойка устойчивая.",
      "Тяни рукоять по диагонали вниз-в сторону, разворачивая корпус.",
      "Возвращай подконтрольно, работая корпусом, а не руками.",
    ],
    primary: ["obliques"],
    secondary: ["abs_upper", "abs_lower", "serratus"],
    stabilizer: ["glute_max", "glute_med", "erector", "delt_front"],
  },

  // ───────────────────────── НОГИ ─────────────────────────
  {
    id: "squat",
    name: "Приседания со штангой",
    category: "legs",
    equipment: "Штанга",
    focus: "Квадрицепс целиком + ягодицы, база на ноги",
    technique: [
      "Штанга на трапециях, ноги на ширине плеч, носки слегка врозь.",
      "Опускайся, отводя таз назад и сгибая колени, спина прямая, колени по линии носков.",
      "Опустись минимум до параллели бёдер с полом, затем мощно встань.",
    ],
    primary: ["quad_rectus", "quad_lateral", "quad_medial", "glute_max"],
    secondary: ["adductors", "ham_biceps", "ham_semi", "erector"],
    stabilizer: ["abs_upper", "abs_lower", "obliques", "calf_gastro", "calf_soleus", "traps_upper", "glute_med"],
  },
  {
    id: "front-squat",
    name: "Фронтальные приседания",
    category: "legs",
    equipment: "Штанга",
    focus: "Квадрицепс с меньшей нагрузкой на поясницу",
    technique: [
      "Штанга на передних дельтах, локти высоко и вперёд.",
      "Приседай строго вертикально, корпус держи прямо, локти не опускай.",
      "Вставай, толкаясь через середину стопы.",
    ],
    primary: ["quad_rectus", "quad_lateral", "quad_medial"],
    secondary: ["glute_max", "adductors", "erector"],
    stabilizer: ["abs_upper", "abs_lower", "traps_upper", "delt_front", "calf_soleus"],
  },
  {
    id: "leg-press",
    name: "Жим ногами",
    category: "legs",
    equipment: "Тренажёр жима ногами",
    focus: "Квадрицепс, безопасно для спины",
    technique: [
      "Стопы на платформе на ширине плеч, поясница прижата к спинке.",
      "Сгибай колени, опуская платформу до угла ~90°.",
      "Выжимай платформу вверх, не разгибая колени в жёсткий замок.",
      "Стопы выше — больше ягодицы и бицепс бедра, ниже — больше квадрицепс.",
    ],
    primary: ["quad_rectus", "quad_lateral", "quad_medial"],
    secondary: ["glute_max", "adductors", "ham_biceps"],
    stabilizer: ["calf_soleus", "abs_lower", "erector"],
  },
  {
    id: "hack-squat",
    name: "Приседания в гакк-тренажёре",
    category: "legs",
    equipment: "Гакк-тренажёр",
    focus: "Внешняя и внутренняя головки квадрицепса",
    technique: [
      "Спина плотно прижата к спинке, стопы на платформе на ширине плеч.",
      "Сгибай колени, опускаясь до глубокого приседа под контролем.",
      "Выжимай платформу вверх через пятки и середину стопы.",
    ],
    primary: ["quad_lateral", "quad_medial", "quad_rectus"],
    secondary: ["glute_max", "adductors"],
    stabilizer: ["calf_soleus", "erector", "abs_lower"],
  },
  {
    id: "leg-extension",
    name: "Разгибание ног в тренажёре",
    category: "legs",
    equipment: "Тренажёр для разгибания ног",
    focus: "Изоляция квадрицепса, акцент на «каплю»",
    technique: [
      "Сидя, спина прижата к спинке, валик на голенях выше стоп.",
      "Разгибай колени, поднимая валик вверх, в верхней точке — короткая пауза.",
      "Опускай подконтрольно, не роняя вес.",
    ],
    primary: ["quad_rectus", "quad_lateral", "quad_medial"],
    secondary: [],
    stabilizer: ["tibialis", "abs_lower"],
  },
  {
    id: "lunges",
    name: "Выпады с гантелями",
    category: "legs",
    equipment: "Гантели",
    focus: "Квадрицепс и ягодицы, работа по одной ноге",
    technique: [
      "Гантели по бокам, шаг вперёд одной ногой.",
      "Опускай таз вниз, оба колена сгибаются до ~90°, переднее колено над стопой.",
      "Оттолкнись передней ногой, возвращаясь в исходное положение.",
    ],
    primary: ["quad_rectus", "quad_lateral", "quad_medial", "glute_max"],
    secondary: ["ham_biceps", "ham_semi", "adductors", "glute_med"],
    stabilizer: ["calf_gastro", "abs_upper", "abs_lower", "obliques", "erector"],
  },
  {
    id: "bulgarian-split-squat",
    name: "Болгарский сплит-присед",
    category: "legs",
    equipment: "Гантели, скамья",
    focus: "Ягодицы и квадрицепс одной ноги, баланс",
    technique: [
      "Задняя нога на скамье, передняя в шаге впереди.",
      "Опускайся вниз, сгибая переднюю ногу до ~90°, корпус слегка вперёд для акцента на ягодицу.",
      "Вставай, толкаясь передней пяткой.",
    ],
    primary: ["glute_max", "quad_rectus", "quad_lateral"],
    secondary: ["quad_medial", "ham_biceps", "adductors", "glute_med"],
    stabilizer: ["calf_gastro", "abs_lower", "obliques", "erector"],
  },
  {
    id: "leg-curl",
    name: "Сгибание ног лёжа/сидя",
    category: "legs",
    equipment: "Тренажёр для сгибания ног",
    focus: "Изоляция бицепса бедра",
    technique: [
      "Лёжа или сидя, валик тренажёра на голенях (за ахиллом).",
      "Сгибай колени, подтягивая валик к ягодицам.",
      "Опускай подконтрольно до полного выпрямления ног.",
    ],
    primary: ["ham_biceps", "ham_semi"],
    secondary: ["calf_gastro"],
    stabilizer: ["glute_max", "erector", "abs_lower"],
  },
  {
    id: "romanian-deadlift",
    name: "Румынская тяга",
    category: "legs",
    equipment: "Штанга / гантели",
    focus: "Бицепс бедра и ягодицы в растяжении",
    technique: [
      "Ноги чуть согнуты, штанга/гантели у бёдер, спина прямая.",
      "Отводи таз назад, опуская вес вдоль ног до растяжения задней поверхности бедра.",
      "Верни корпус в исходное за счёт бёдер и ягодиц, не круглить спину.",
    ],
    primary: ["ham_biceps", "ham_semi", "glute_max"],
    secondary: ["erector", "adductors"],
    stabilizer: ["traps_upper", "forearm_flexors", "abs_upper", "lats_lower"],
  },
  {
    id: "glute-bridge",
    name: "Ягодичный мостик со штангой",
    category: "legs",
    equipment: "Штанга / собственный вес",
    focus: "Изоляция большой ягодичной",
    technique: [
      "Лопатки на скамье или полу, колени согнуты, штанга на бёдрах.",
      "Поднимай таз вверх, сжимая ягодицы в верхней точке до прямой линии корпус-бедро.",
      "Опускай подконтрольно, не расслабляя ягодицы полностью внизу.",
    ],
    primary: ["glute_max"],
    secondary: ["ham_biceps", "ham_semi", "quad_rectus"],
    stabilizer: ["erector", "abs_lower", "adductors", "glute_med"],
  },
  {
    id: "reverse-lunge",
    name: "Выпады назад",
    category: "legs",
    equipment: "Гантели / собственный вес",
    focus: "Ягодицы, меньше нагрузки на колено",
    technique: [
      "Шаг одной ногой назад, опускай таз вниз до угла ~90° в обоих коленях.",
      "Вес тела — на передней ноге, ягодица активно включена.",
      "Оттолкнись передней ногой, возвращаясь в исходное положение.",
    ],
    primary: ["glute_max", "quad_rectus", "quad_lateral"],
    secondary: ["ham_biceps", "glute_med", "adductors", "quad_medial"],
    stabilizer: ["calf_gastro", "abs_lower", "obliques", "erector"],
  },
  {
    id: "hip-abduction",
    name: "Отведение бедра в тренажёре",
    category: "legs",
    equipment: "Тренажёр отведения бёдер",
    focus: "Средняя ягодичная — форма таза сбоку",
    technique: [
      "Сидя в тренажёре, колени и бёдра прижаты к упорам.",
      "Разводи бёдра в стороны, сжимая ягодицы в конечной точке.",
      "Своди подконтрольно, не отпуская вес рывком.",
    ],
    primary: ["glute_med"],
    secondary: ["glute_max"],
    stabilizer: ["erector", "obliques", "abs_lower"],
  },
  {
    id: "hip-adduction",
    name: "Сведение ног в тренажёре",
    category: "legs",
    equipment: "Тренажёр сведения бёдер",
    focus: "Приводящие — внутренняя поверхность бедра",
    technique: [
      "Сидя в тренажёре, ноги разведены и упираются во внутренние подушки.",
      "Своди бёдра вместе, сжимая внутреннюю поверхность.",
      "Разводи медленно, до комфортного растяжения.",
    ],
    primary: ["adductors"],
    secondary: ["ham_semi", "glute_max"],
    stabilizer: ["abs_lower", "erector"],
  },
  {
    id: "standing-calf-raise",
    name: "Подъём на носки стоя",
    category: "legs",
    equipment: "Тренажёр / штанга",
    focus: "Икроножная (верхний объём голени)",
    technique: [
      "Стоя, носки на возвышении, пятки свисают вниз, ноги прямые.",
      "Поднимайся на носки максимально высоко, пауза вверху.",
      "Опускайся, растягивая икры внизу, без рывков.",
    ],
    primary: ["calf_gastro"],
    secondary: ["calf_soleus"],
    stabilizer: ["tibialis", "quad_rectus", "abs_upper", "erector"],
  },
  {
    id: "seated-calf-raise",
    name: "Подъём на носки сидя",
    category: "legs",
    equipment: "Тренажёр для икр сидя",
    focus: "Камбаловидная (толщина голени под икроножной)",
    technique: [
      "Сидя, валик тренажёра на коленях, носки на платформе, колени согнуты 90°.",
      "Поднимайся на носки, сокращая икры в верхней точке.",
      "Опускайся плавно до полного растяжения.",
    ],
    primary: ["calf_soleus"],
    secondary: ["calf_gastro"],
    stabilizer: ["tibialis"],
  },
  {
    id: "tibialis-raise",
    name: "Подъём носков на себя",
    category: "legs",
    equipment: "Собственный вес / тренажёр",
    focus: "Передняя большеберцовая — баланс голени, здоровье колена",
    technique: [
      "Стоя пятками на возвышении или сидя с грузом на носках.",
      "Поднимай носки на себя максимально высоко.",
      "Опускай медленно до полного растяжения передней части голени.",
    ],
    primary: ["tibialis"],
    secondary: [],
    stabilizer: ["quad_rectus", "abs_lower"],
  },
];

export function getExercise(id: string): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id);
}
